New example using the query param for Device Farm's list devices API
aws/aws-cli pull request #4396
Opened 2019-08-09 17:13 UTC by jamesknowsbest

*Issue #, if available:*
NA

*Description of changes:*
Added an example of using the query param with Device Farm's list-devices API

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-05-19 22:27 UTC, justindho requested changes
Hi @jamesknowsbest, thanks for the contribution! Apologies for it taking so long to get back to you. I just had some comments regarding formatting/wording. Would you still be interested in pushing this PR forward to get it merged?

2022-05-19 22:27 UTC, justindho commented on awscli/examples/devicefarm/list-devices.rst
> +aws devicefarm list-devices --region us-west-2 --query 'devices[?platform==`IOS` && fleetType==`PRIVATE`].[name, os, instances[].udid]'
We can probably remove the `--region us-west-2` to maintain consistency between all the different service command/subcommand examples (we'll just assume that the user has already configured their region somewhere else, such as in their `~/.aws/config` or via an environment variable).

2022-05-19 22:27 UTC, justindho commented on awscli/examples/devicefarm/list-devices.rst
> +### To list all iOS private devices and their UDID value
Would you be able to format and phrase this file similar to how other rst example files are formatted? DynamoDB's `create-table.rst` example file could be a good reference: https://raw.githubusercontent.com/aws/aws-cli/develop/awscli/examples/dynamodb/create-table.rst

2023-03-15 17:12 UTC, tim-finnigan commented
Closing as we have not heard back regarding changes requested on this PR.

2023-03-15 17:12 UTC, closed without merging