updating README to recommend v2 installers
aws/aws-cli pull request #4916
Opened 2020-02-04 23:43 UTC by nateprewitt

Updating README to recommend pre-built installers for AWS CLI v2.

2020-02-04 23:55 UTC, timoschilling requested changes
all links aren't working (cloudfront 403)

2020-02-04 23:58 UTC, nateprewitt commented
Thanks @timoschilling! We're currently getting the routing setup, we'll merge the PR after that's completed.

2020-02-05 17:58 UTC, stealthycoin commented on README.rst
> +* `MacOS executable installer <https://awscli.amazonaws.com/AWSCLIV2.pkg>`__
MacOS pkg installer

2020-02-05 18:05 UTC, nateprewitt commented on README.rst
> +* `MacOS executable installer <https://awscli.amazonaws.com/AWSCLIV2.pkg>`__
Good call, updated.

2020-02-06 01:09 UTC, kyleknap approved these changes
Nice! Looks good. :ship:

2020-02-06 01:23 UTC, stealthycoin approved these changes

2020-02-06 21:00 UTC, merged