Example for multiple environment variables in shorthand
aws/aws-cli pull request #5135
Opened 2020-04-21 07:59 UTC by ydbendasan

When using through CI/CD pipelines, the json option may not be available. It took me the better part of 2 days to discover how to set multiple environment variables in shorthand form so an example here would be very useful for other beginners.

*Issue #, if available:*

*Description of changes:*
Added an example to --option-settings to show how multiple settings can be set using shorthand form.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-05-19 20:16 UTC, justindho requested changes
@ydbendasan Thanks for the contribution! The changes look pretty good to me. Just had a couple minor comments.

2022-05-19 20:16 UTC, justindho commented on awscli/examples/elasticbeanstalk/update-environment.rst
> +**To set multiple environment variables in shorthand form**
Nit: Can we change this to `**To set multiple environment variables using shorthand syntax**`? That way, we are consistent with the vocabulary we use when referring to "shorthand syntax".

2022-05-19 20:16 UTC, justindho commented on awscli/examples/elasticbeanstalk/update-environment.rst
> +aws elasticbeanstalk update-environment --environment-name my-env --option-settings Namespace=aws:elasticbeanstalk:application:environment,OptionName=PARAM1,Value=ParamValue Namespace=aws:elasticbean
Would you be able to add a similar example to [create-environment.rst](https://github.com/aws/aws-cli/blob/develop/awscli/examples/elasticbeanstalk/create-environment.rst)? That should cover our bases with respect to setting multiple environment variables using the `--option-settings` parameter for the `elasticbeanstalk` command.

2023-08-02 20:59 UTC, tim-finnigan commented
Closing as we have not heard back on this PR for over a year. Please refer to feedback above if you would like to revisit this.

2023-08-02 20:59 UTC, closed without merging

2024-05-03 12:53 UTC, amberkushwaha commented
closing as we have not heard back on this PR for over a year,Please refer to feedback above if you would like to revisit thi.

2025-05-05 10:29 UTC, amberkushwaha commented
[aqua-registry](https://github.com/garysassano/aqua-registry) Public
Forked from [aquaproj/aqua-registry](https://github.com/aquaproj/aqua-registry)
aqua's Standard Registry
 YAML MIT License Updated last week