Update create-data-catalog.rst
aws/aws-cli pull request #6122
Opened 2021-04-26 17:39 UTC by DavidIndrawes2

Was using the wrong parameter name

*Issue #, if available:*
Wrong parameter name on an example 

*Description of changes:*
Fixed the example

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-04-27 17:21 UTC, kdaily requested changes
Hi @DavidIndrawes2, thanks for catching that. Can you fix the change to the last line? It doesn't seem like you made any changes, but maybe a new line was added or removed. Please squash your commits afterwards. If you need any help with that, let us know!

2021-04-28 15:20 UTC, DavidIndrawes2 commented
hey @kdaily I have pushed an update, it was the ^M line ending

2021-04-29 20:19 UTC, kdaily approved these changes

2021-05-28 20:16 UTC, kyleknap approved these changes
Thanks! Merging.

2021-05-28 20:16 UTC, merged