Append `aws-chunked` to `Content-Encoding` header if present
aws/aws-cli pull request #7663
Opened 2023-02-13 20:25 UTC by stealthycoin

sourced from https://github.com/boto/botocore/pull/2859

2023-02-13 20:43 UTC, dlm6693 commented
@stealthycoin I think you need to add this commit as well: https://github.com/boto/botocore/commit/8d2141e1a94bc1477d032457dec5de91d632d95d

2023-02-13 23:59 UTC, dlm6693 requested changes
lgtm! Just update the changelog and we can ship it.

2023-02-13 23:59 UTC, dlm6693 commented on .changes/next-release/bugfix-s3-10151.json
> +  "description": "boto3 no longer overwrites user supplied `Content-Encoding` with `aws-chunked` when user also supplies `ChecksumAlgorithm`."
We should change the description to be for `aws-cli` not `boto3`

2023-02-14 16:35 UTC, kyleknap approved these changes
:ship:

2023-02-14 18:57 UTC, dlm6693 approved these changes

2023-02-14 18:58 UTC, merged