Example updates for s3
aws/aws-cli pull request #8249
Opened 2023-10-18 16:06 UTC by elysahall

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-10-30 16:40 UTC, kdaily requested changes
Looks good overall, only changes I saw are in:

awscli/examples/s3/sync.rst

Looks like a find/replace was used and put uppercase `S3` inside commands for the S3 uri, which should be lowercase (`s3://`).

2023-10-30 16:40 UTC, kdaily commented on awscli/examples/s3/sync.rst
> +    aws s3 sync . S3://mybucket
This should still be lowercase.

2023-10-30 16:40 UTC, kdaily commented on awscli/examples/s3/sync.rst
> +    upload: test.txt to S3://mybucket/test.txt
Lowercase

2023-10-30 16:40 UTC, kdaily commented on awscli/examples/s3/sync.rst
> +    upload: test2.txt to S3://mybucket/test2.txt
Lowercase

2023-10-30 16:40 UTC, kdaily commented on awscli/examples/s3/sync.rst
> +    aws s3 sync S3://mybucket S3://mybucket2
Lowercase

2023-10-31 18:28 UTC, kdaily approved these changes

2024-01-26 17:40 UTC, kyleknap approved these changes

2024-01-26 17:41 UTC, merged