Add CLI examples for CloudWatch OAM
aws/aws-cli pull request #8971
Opened 2024-10-14 07:24 UTC by ashishbharadwajm

*Issue #, if available:*

*Description of changes:*

Adding example CLI commands for Amazon CloudWatch Observability Access Manager: https://docs.aws.amazon.com/cli/latest/reference/oam/

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-10-30 19:19 UTC, elysahall requested changes

2024-10-30 19:19 UTC, elysahall commented on awscli/examples/oam/delete-link.rst
> +
There is a missing output section. If this command produces no output please add the appropriate line.
https://aws.github.io/aws-cli/docs_styleguide.html#output

2024-10-30 19:19 UTC, elysahall commented on awscli/examples/oam/delete-sink.rst
> +
Same here. There is a missing output section. If this command produces no output please add the appropriate line.
https://aws.github.io/aws-cli/docs_styleguide.html#output

2024-10-30 19:19 UTC, elysahall commented on awscli/examples/oam/get-link.rst
> +}
```suggestion
    }
```

2024-10-30 19:19 UTC, elysahall commented on awscli/examples/oam/get-sink-policy.rst
> +}
```suggestion
    }
```

2024-10-30 19:19 UTC, elysahall commented on awscli/examples/oam/put-sink-policy.rst
> +        --policy "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"arn:aws:iam::123456789111:root\"},\"Action\":[\"oam:CreateLink\",\"oam:UpdateLink\"],\"Reso
```suggestion
        --policy '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"AWS":"arn:aws:iam::123456789111:root"},"Action":["oam:CreateLink","oam:UpdateLink"],"Resource":"*","Condition":{"ForAllValues:StringEquals":{"oam:ResourceTypes":["AWS::Logs::LogGroup","AWS::CloudWatch::Metric","AWS::XRay::Trace","AWS::ApplicationInsights::Application"]}}}]}' \
```

2024-10-30 19:19 UTC, elysahall commented on awscli/examples/oam/tag-resource.rst
> +        --tags team=Devops
```suggestion
        --tags team=Devops

This command produces no output.
```

2024-10-30 19:19 UTC, elysahall commented on awscli/examples/oam/tag-resource.rst
> +The following ``tag-resource`` example tags a sink ``arn:aws:oam:us-east-2:123456789012:sink/a1b2c3d4-5678-90ab-cdef-example12345``. If the command succeeds, no output is returned. ::
```suggestion
The following ``tag-resource`` example tags a sink ``arn:aws:oam:us-east-2:123456789012:sink/a1b2c3d4-5678-90ab-cdef-example12345``. ::
```

2024-10-30 19:19 UTC, elysahall commented on awscli/examples/oam/untag-resource.rst
> +        --tag-keys team
```suggestion
        --tag-keys team

This command produces no output.
```

2024-10-30 19:19 UTC, elysahall commented on awscli/examples/oam/untag-resource.rst
> +The following ``untag-resource`` example removes a tag with the key ``team`` from Sink ``arn:aws:oam:us-east-2:123456789012:sink/a1b2c3d4-5678-90ab-cdef-example12345``. If the command succeeds, no ou
```suggestion
The following ``untag-resource`` example removes a tag with the key ``team`` from Sink ``arn:aws:oam:us-east-2:123456789012:sink/a1b2c3d4-5678-90ab-cdef-example12345``. ::
```

2024-11-13 17:57 UTC, elysahall requested changes
Missed a double colon causing incorrect rendering. Thanks!

2024-11-14 07:18 UTC, ashishbharadwajm commented on awscli/examples/oam/untag-resource.rst
> +The following ``untag-resource`` example removes a tag with the key ``team`` from Sink ``arn:aws:oam:us-east-2:123456789012:sink/a1b2c3d4-5678-90ab-cdef-example12345``.
Published the new commit with suggested changes

2024-12-27 04:07 UTC, closed without merging