Add CLI examples for CloudWatch Synthetics
aws/aws-cli pull request #8977
Opened 2024-10-16 09:23 UTC by ashishbharadwajm

*Issue #, if available:*

*Description of changes:*

Adding example CLI commands for Amazon CloudWatch Synthetics: https://docs.aws.amazon.com/cli/latest/reference/synthetics/

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-11-11 22:33 UTC, elysahall requested changes
Hi Ashish,
Thank you for your command example submission. I've finished reviewing your pull request. Please fix these formatting issues and push your updated commit. Thanks!

2024-11-11 22:33 UTC, elysahall commented on awscli/examples/synthetics/start-canary.rst
> +The following ``start-canary`` example runs a canary named ``demo_canary``.
```suggestion
The following ``start-canary`` example runs a canary named ``demo_canary``. ::
```

2024-11-11 22:33 UTC, elysahall commented on awscli/examples/synthetics/stop-canary.rst
> +**To Stop a canary **
```suggestion
**To stop a canary **
```

2024-11-11 22:33 UTC, elysahall commented on awscli/examples/synthetics/stop-canary.rst
> +The following ``stop-canary`` example stops the canary named ``demo_canary``.
```suggestion
The following ``stop-canary`` example stops the canary named ``demo_canary``. ::
```

2024-11-11 22:33 UTC, elysahall commented on awscli/examples/synthetics/tag-resource.rst
> +**Example 1: To Assign a tag to the canary**
```suggestion
**Example 1: To assign a tag to the canary**
```

2024-11-11 22:33 UTC, elysahall commented on awscli/examples/synthetics/tag-resource.rst
> +The following ``tag-resource`` example assigns a tag to the canary named ``demo_canary``.
```suggestion
The following ``tag-resource`` example assigns a tag to the canary named ``demo_canary``. ::
```

2024-11-11 22:33 UTC, elysahall commented on awscli/examples/synthetics/tag-resource.rst
> +**Example 2: To Assign a tag to the group**
```suggestion
**Example 2: To assign a tag to the group**
```

2024-11-11 22:33 UTC, elysahall commented on awscli/examples/synthetics/tag-resource.rst
> +The following ``tag-resource`` example assigns a tag to the group named ``demo_group``.
```suggestion
The following ``tag-resource`` example assigns a tag to the group named ``demo_group``. ::
```

2024-11-11 22:33 UTC, elysahall commented on awscli/examples/synthetics/untag-resource.rst
> +**Example 1: To Remove a tag from the canary**
```suggestion
**Example 1: To remove a tag from the canary**
```

2024-11-11 22:33 UTC, elysahall commented on awscli/examples/synthetics/untag-resource.rst
> +The following ``untag-resource`` example removes a tag from the canary named ``demo_canary``.
```suggestion
The following ``untag-resource`` example removes a tag from the canary named ``demo_canary``. ::
```

2024-11-11 22:33 UTC, elysahall commented on awscli/examples/synthetics/untag-resource.rst
> +**Example 2: To Remove a tag from the group**
```suggestion
**Example 2: To remove a tag from the group**
```

2024-11-11 22:33 UTC, elysahall commented on awscli/examples/synthetics/untag-resource.rst
> +The following ``untag-resource`` example assigns a removes a tag from the group named ``demo_group``.
```suggestion
The following ``untag-resource`` example assigns a removes a tag from the group named ``demo_group``. ::
```

2024-11-11 23:11 UTC, ashishdhingra commented
@elysahall I guess you tagged wrong person. Please reach out to @ashishbharadwajm.

2024-11-14 07:41 UTC, ashishbharadwajm commented
> Hi Ashish, Thank you for your command example submission. I've finished reviewing your pull request. Please fix these formatting issues and push your updated commit. Thanks!

Thank you for the review. Published the new commit with the suggested changes.

2024-12-27 04:11 UTC, closed without merging