[v2] Add CRC64NVME to vendored botocore
aws/aws-cli pull request #9082
Opened 2024-11-18 20:38 UTC by aemous

*Issue #, if available:*
- https://github.com/boto/botocore/pull/3273

*Description of changes:*
- Enables CRC64NVME checksum calculation

*Description of tests:*
- Ran and passed the tests added by botocore.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-11-18 20:42 UTC, nateprewitt reviewed
I think we'll need to [raise the floor](https://github.com/aws/aws-cli/blob/d9b2f70e0f7d6628b1f9d2b8957b15ecbdbafc7c/pyproject.toml#L44) on the CRT to allow this change, otherwise it's going to start failing for customers that aren't eagerly upgrading their dependencies.

2024-11-18 20:44 UTC, ashovlin commented
Should this target a feature branch until the rest of the corresponding work is ready? I think the `_ALGORITHMS_PRIORITY_LIST` change can influence current behavior.

2024-11-19 20:46 UTC, hssyoo requested changes

2024-11-19 20:46 UTC, hssyoo commented on awscli/botocore/httpchecksum.py
> +class CrtCrc64NvmeChecksum(BaseChecksum):
nit: Newlines between methods.

2024-11-19 21:28 UTC, hssyoo approved these changes

2024-11-20 15:34 UTC, merged