Add CLI examples for CloudWatch NetworkFlowMonitor
aws/aws-cli pull request #9127
Opened 2024-12-09 23:26 UTC by chaitanyagummadi

*Issue #, if available:*

*Description of changes:*
Add CLI examples for Amazon CloudWatch NetWork Flow Monitor service:
https://docs.aws.amazon.com/cli/latest/reference/networkflowmonitor/#cli-aws-networkflowmonitor

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2025-01-08 17:24 UTC, elysahall requested changes
Hi @chaitanyagummadi,
It looks like most of your examples are missing "for more information" links. Other than that there was only one grammar fix. After you finish the updates, commit and push your changes and we should be good to send for maintainer review.

2025-01-08 17:24 UTC, elysahall commented on awscli/examples/networkflowmonitor/create-scope.rst
> +The following ``create-scope`` creates a scope that includes a set of resources for which Network Flow Monitor will generate network traffic metrics. ::
```suggestion
The following ``create-scope`` example creates a scope that includes a set of resources for which Network Flow Monitor will generate network traffic metrics. ::
```

2025-01-08 17:24 UTC, elysahall commented on awscli/examples/networkflowmonitor/get-query-results-workload-insights-top-contributors-data.rst
> +    }
Every example needs a for more information link.
https://aws.github.io/aws-cli/docs_styleguide.html#for-more-information-link

2025-01-08 17:24 UTC, elysahall commented on awscli/examples/networkflowmonitor/get-query-results-workload-insights-top-contributors.rst
> +    }
Every example needs a for more information link.
https://aws.github.io/aws-cli/docs_styleguide.html#for-more-information-link

2025-01-08 17:24 UTC, elysahall commented on awscli/examples/networkflowmonitor/get-query-status-monitor-top-contributors.rst
> +    }
Every example needs a for more information link.
https://aws.github.io/aws-cli/docs_styleguide.html#for-more-information-link

2025-01-08 17:24 UTC, elysahall commented on awscli/examples/networkflowmonitor/get-query-status-workload-insights-top-contributors-data.rst
> +    }
Every example needs a for more information link.
https://aws.github.io/aws-cli/docs_styleguide.html#for-more-information-link

2025-01-08 17:24 UTC, elysahall commented on awscli/examples/networkflowmonitor/get-query-status-workload-insights-top-contributors.rst
> +    }
Every example needs a for more information link.
https://aws.github.io/aws-cli/docs_styleguide.html#for-more-information-link

2025-01-08 17:24 UTC, elysahall commented on awscli/examples/networkflowmonitor/list-tags-for-resource.rst
> +    }
Every example needs a for more information link.
https://aws.github.io/aws-cli/docs_styleguide.html#for-more-information-link

2025-01-08 17:24 UTC, elysahall commented on awscli/examples/networkflowmonitor/start-query-monitor-top-contributors.rst
> +    }
Every example needs a for more information link.
https://aws.github.io/aws-cli/docs_styleguide.html#for-more-information-link

2025-01-08 17:24 UTC, elysahall commented on awscli/examples/networkflowmonitor/start-query-workload-insights-top-contributors.rst
> +    }
Every example needs a for more information link.
https://aws.github.io/aws-cli/docs_styleguide.html#for-more-information-link

2025-01-08 17:24 UTC, elysahall commented on awscli/examples/networkflowmonitor/stop-query-monitor-top-contributors.rst
> +This command produces no output.
Every example needs a for more information link.
https://aws.github.io/aws-cli/docs_styleguide.html#for-more-information-link

2025-01-08 17:24 UTC, elysahall commented on awscli/examples/networkflowmonitor/stop-query-workload-insights-top-contributors-data.rst
> +This command produces no output.
Every example needs a for more information link.
https://aws.github.io/aws-cli/docs_styleguide.html#for-more-information-link

2025-01-08 17:24 UTC, elysahall commented on awscli/examples/networkflowmonitor/stop-query-workload-insights-top-contributors.rst
> +This command produces no output.
Every example needs a for more information link.
https://aws.github.io/aws-cli/docs_styleguide.html#for-more-information-link

2025-01-08 17:24 UTC, elysahall commented on awscli/examples/networkflowmonitor/tag-resource.rst
> +This command produces no output.
Every example needs a for more information link.
https://aws.github.io/aws-cli/docs_styleguide.html#for-more-information-link

2025-01-08 17:24 UTC, elysahall commented on awscli/examples/networkflowmonitor/untag-resource.rst
> +This command produces no output.
Every example needs a for more information link.
https://aws.github.io/aws-cli/docs_styleguide.html#for-more-information-link

2025-01-22 00:15 UTC, elysahall approved these changes
LGTM, sending for maintainer review.

2025-01-23 15:08 UTC, aemous requested changes
Left a couple of comments and nits I'd like to see addressed before we merge this

2025-01-23 15:08 UTC, aemous commented on awscli/examples/networkflowmonitor/start-query-monitor-top-contributors.rst
> +The following ``start-query-monitor-top-contributors``  example starts the query which returns a queryId to retrieve the top contributors. ::
nit: queryId -> query ID

2025-01-23 15:08 UTC, aemous commented on awscli/examples/networkflowmonitor/start-query-workload-insights-top-contributors-data.rst
> +The following ``start-query-workload-insights-top-contributors-data``  example starts the query which returns a queryId to retrieve the top contributors. ::
nit: queryId -> query ID

2025-01-23 15:08 UTC, aemous commented on awscli/examples/networkflowmonitor/start-query-workload-insights-top-contributors.rst
> +The following ``start-query-workload-insights-top-contributors``  example starts the query which returns a queryId to retrieve the top contributors. ::
nit: queryId -> query ID

2025-01-23 15:08 UTC, aemous commented on awscli/examples/networkflowmonitor/untag-resource.rst
> +**To remove a tag to the specified resource**
To remove a tag to the specified resource -> To remove a tag from the specified resource

2025-01-23 15:08 UTC, aemous commented on awscli/examples/networkflowmonitor/untag-resource.rst
> +The following ``untag-resource`` example removes a tag to the monitor in the specified account. ::
example removes a tag to the monitor -> example removes a tag from the monitor

2025-01-30 18:05 UTC, chaitanyagummadi commented
@aemous I made a new commit fixing all the 7 files. Awaiting your review. Thanks!

2025-01-31 20:54 UTC, aemous approved these changes
LGTM

2025-01-31 21:06 UTC, merged