Lint format base repo extended
aws/aws-cli pull request #9171
Opened 2024-12-24 19:54 UTC by kdaily

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2025-02-12 15:24 UTC, aemous commented
Looks like there's merge conflicts. Can we get those resolved ?

2025-02-14 00:15 UTC, nateprewitt requested changes
Handful of fixes, we may want to try running this with [UP032](https://docs.astral.sh/ruff/rules/f-string/#f-string-up032) to automate some of the string cleanup.

2025-02-14 00:15 UTC, nateprewitt commented on awscli/alias.py
> +                % (self._alias_name, e, self._alias_value)
nit; this should be an f-string (or at the least `.format()`). We've generally been moving away from the % syntax.

2025-02-14 00:15 UTC, nateprewitt commented on awscli/alias.py
> +                        % (parsed_param, self._alias_name))
f-string

2025-02-14 00:15 UTC, nateprewitt commented on awscli/alias.py
> +                    'Using shadowed command object: %s ' 'for alias: %s',
This is a log statement, the % syntax is fine, we just want to remove the extraneous quotes and whitespace from the line collapse.
```suggestion
                    'Using shadowed command object: %s for alias: %s',
```

2025-02-14 00:15 UTC, nateprewitt commented on awscli/alias.py
> +                "Delegating to proxy sub-command with new alias " "args: %s",
```suggestion
                "Delegating to proxy sub-command with new alias args: %s",
```

2025-02-14 00:15 UTC, nateprewitt commented on awscli/argprocess.py
> +        full_message = "Error parsing parameter '%s': %s" % (cli_name, message)
f-string
```suggestion
        full_message = f"Error parsing parameter '{cli_name}': {message}"
```

2025-02-14 00:15 UTC, nateprewitt commented on awscli/argprocess.py
> +        )
```suggestion
        full_message = f"Unknown key '{key}', valid choices are: {valid_keys}"
```

2025-02-14 00:15 UTC, nateprewitt commented on awscli/argprocess.py
> +        'load-cli-arg.%s.%s.%s' % (service_name, operation_name, param_name),
```suggestion
        f'load-cli-arg.{service_name}.{operation_name}.{param_name}'
```

2025-02-14 00:15 UTC, nateprewitt commented on awscli/argprocess.py
> +            cli_name, "Invalid JSON: %s\nJSON received: %s" % (e, value)
```suggestion
            cli_name, f"Invalid JSON: {e}\nJSON received: {value}"
```

2025-02-14 00:15 UTC, nateprewitt commented on awscli/argprocess.py
> +            return '%s %s1 %s2 %s3' % (
f-string

2025-02-14 00:15 UTC, nateprewitt commented on awscli/arguments.py
> +            'process-cli-arg.%s.%s' % (service_name, operation_name),
```suggestion
            f'process-cli-arg.{service_name}.{operation_name}',
```

2025-02-14 00:15 UTC, nateprewitt commented on awscli/clidocs.py
> +                    '``%s``' % a.cli_name
```suggestion
                    f'``{a.cli_name}``'
```

2025-02-14 00:15 UTC, nateprewitt commented on awscli/clidocs.py
> +            label='cli:%s' % related_item, text=related_item
```suggestion
            label=f'cli:{related_item}', text=related_item
```

2025-02-14 00:15 UTC, nateprewitt commented on awscli/clidocs.py
> +        link = '%s/%s/%s' % (
f-string

2025-02-14 00:15 UTC, nateprewitt commented on awscli/clidocs.py
> +                    '%s, ...'
f-string or .format()

2025-02-14 00:15 UTC, nateprewitt commented on awscli/clidocs.py
> +                    '"%s": %s'
f-string or .format()

2025-02-14 00:15 UTC, nateprewitt commented on awscli/clidocs.py
> +            refname='cli:aws help %s' % self.help_command.name, link=''
```suggestion
            refname=f'cli:aws help {self.help_command.name}', link=''
```

2025-02-14 00:15 UTC, nateprewitt commented on awscli/clidocs.py
> +                    label='cli:aws help %s' % topic_name, text=topic_name
```suggestion
                    label=f'cli:aws help {topic_name}', text=topic_name
```

2025-02-14 00:15 UTC, nateprewitt commented on awscli/clidocs.py
> +            refname='cli:aws help %s' % self.help_command.name, link=''
```suggestion
            refname=f'cli:aws help {self.help_command.name}', link=''
```

2025-02-14 17:29 UTC, kdaily commented
> Handful of fixes, we may want to try running this with [UP032](https://docs.astral.sh/ruff/rules/f-string/#f-string-up032) to automate some of the string cleanup.

I'm not sure why these aren't changed automatically, `UP302` is enabled:

https://github.com/aws/aws-cli/blob/dbfa39301e8535b761f2ec42e051ba282442cb0f/pyproject.toml#L178

2025-03-07 18:26 UTC, nateprewitt approved these changes
One last one to fix and then I think you're good.

2025-03-07 18:26 UTC, nateprewitt commented on awscli/shorthand.py
> +        msg = ("Expected: '%s', received: '%s' for input:\n" "%s") % (
```suggestion
        msg = ("Expected: '%s', received: '%s' for input:\n %s") % (
```

2025-03-10 16:08 UTC, merged