adding CLI examples for App signals
aws/aws-cli pull request #9176
Opened 2024-12-27 07:00 UTC by khyathisri

*Issue #, if available:*

*Description of changes:*

Adding CLI examples for Application signals

https://docs.aws.amazon.com/cli/latest/reference/application-signals/#cli-aws-application-signals

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2025-01-22 00:43 UTC, elysahall requested changes
Hi @khyathisri 
Thank you for your command example submission! There were some formatting issues that need to be resolved before I can send for maintainer review.

Please fix all requested formatting issues, and be sure to fix your links in every file, and push your updates for a second review.

Thanks!

2025-01-22 00:43 UTC, elysahall commented on awscli/examples/application-signals/batch-get-service-level-objective-budget-report.rst
> +For more information, see `<https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Application-Monitoring-Sections.html>`__ in the *Amazon CloudWatch User Guide*.
```suggestion
For more information, see `Application Signals <https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Application-Monitoring-Sections.html>`__ in the *Amazon CloudWatch User Guide*.
```

All your for more information links are missing the title portion of the formatting and are therefore display broken. Please fix the URLs in all your submitted files to the following format: 

```
`This is the topic title <https://link.to.the/topic/page>`__
```
https://aws.github.io/aws-cli/docs_styleguide.html#for-more-information-link

2025-01-22 00:43 UTC, elysahall commented on awscli/examples/application-signals/create-service-level-objective.rst
> +The file ``sli-config`` is a JSON documnet in the current folder.
```suggestion
Contents of ``sli-config.json``::
```

2025-01-22 00:43 UTC, elysahall commented on awscli/examples/application-signals/delete-service-level-objective.rst
> +    --id "arn:aws:application-signals:us-east-1:123456789101:slo/SLOName"
```suggestion
        --id "arn:aws:application-signals:us-east-1:123456789101:slo/SLOName"
```

2025-01-22 00:43 UTC, elysahall commented on awscli/examples/application-signals/delete-service-level-objective.rst
> +Output::
```suggestion
```

2025-01-22 00:43 UTC, elysahall commented on awscli/examples/application-signals/delete-service-level-objective.rst
> +    This command produces no output.
```suggestion
This command produces no output.
```

2025-01-22 00:43 UTC, elysahall commented on awscli/examples/application-signals/start-discovery.rst
> +Output::
```suggestion
```

2025-01-22 00:43 UTC, elysahall commented on awscli/examples/application-signals/start-discovery.rst
> +    This command produces no output.
```suggestion
This command produces no output.
```

2025-01-22 00:43 UTC, elysahall commented on awscli/examples/application-signals/tag-resource.rst
> +Output::
```suggestion
```

2025-01-22 00:43 UTC, elysahall commented on awscli/examples/application-signals/tag-resource.rst
> +    This command produces no output.
```suggestion
This command produces no output.
```

2025-01-22 00:43 UTC, elysahall commented on awscli/examples/application-signals/untag-resource.rst
> +Output::
```suggestion
```

2025-01-22 00:43 UTC, elysahall commented on awscli/examples/application-signals/untag-resource.rst
> +    This command produces no output.
```suggestion
This command produces no output.
```

2025-02-09 10:30 UTC, khyathisri reviewed
Hello @elysahall,

I have made the suggested changes, kindly take a look and let me know if any other modifications are required.

Thank you!

2025-03-19 20:35 UTC, ashovlin reviewed
Added a few more comments from the second pass.

2025-07-18 12:38 UTC, khyathisri commented
Hello @ashovlin,

I have made the suggested changes, kindly take a look and let me know if any other modifications are required.

Thank you!

2025-08-13 13:59 UTC, ashovlin approved these changes

2025-08-19 14:36 UTC, ashovlin commented on awscli/examples/application-signals/delete-service-level-objective.rst
> +Output::
Can you remove the `Output::` line from the commands that don't have any. It's actually invalid .rst, hence the test failures.

2025-08-19 14:36 UTC, ashovlin commented on awscli/examples/application-signals/tag-resource.rst
> +Output::
Can you remove the `Output::` line from the commands that don't have any. It's actually invalid .rst, hence the test failures.

2025-08-19 14:36 UTC, ashovlin commented on awscli/examples/application-signals/start-discovery.rst
> +Output::
Can you remove the `Output::` line from the commands that don't have any. It's actually invalid .rst, hence the test failures.

2025-08-19 14:37 UTC, ashovlin commented on awscli/examples/application-signals/untag-resource.rst
> +Output::
Can you remove the `Output::` line from the commands that don't have any. It's actually invalid .rst, hence the test failures.

2025-08-19 14:43 UTC, ashovlin commented on awscli/examples/application-signals/tag-resource.rst
> +        -—tags '{"Key":"test","Value":"value"}'
Both of these ended up with a non-ASCII dash, can you make sure they're only `--`?

2025-08-19 14:44 UTC, ashovlin commented on awscli/examples/application-signals/untag-resource.rst
> +        -—tag-keys "test"
Both of these ended up with a non-ASCII dash, can you make sure they're only `--`?

2025-08-19 14:46 UTC, ashovlin commented on awscli/examples/application-signals/list-service-dependents.rst
> +        -—key-attributes Environment=generic:default,Name=PetSite,Type=Service
Lines 6 and 8 ended up with a non-ASCII dash, can you make sure they're only `--`?

2025-08-21 16:33 UTC, khyathisri commented
Hello @ashovlin ,

I've implemented the changes. Could you please review them and advise if any further adjustments are necessary?

2025-08-25 21:23 UTC, merged

2025-08-25 21:23 UTC, ashovlin commented
@khyathisri looks good, thanks for all of the tweaks! I've merged this for tomorrow's release.